export const frequentlyQuestions = "PREGUNTAS FRECUENTES";
export const howCanIBuy = "¿Como Realizo una Compra?";
export const isSimple = "Es realmente muy simple. Regístrate ingresando la siguiente información:";
export const nameAndLastName = "-Nombre y Apellido";
export const dni = "-DNI";
export const payment = "-Completar preferencia de pago";
export const chooseProduct = "Luego podes navegar por todas las categorías de productos del sitio e ingresar al producto para ver sus detalles:";
export const choosingCharac = " Selecciona el color y talle de tu preferencia y hace click en “Agregar al carrito. En este paso, podes seguir navegando el sitio y agregar más productos al carrito, o bien podes “Proceder a Comprar” y así finalizar tu pedido. Dentro del Resumen de tu pedido, completa la información solicitada y podrás Proceder a Pagar";
export const paymentMethod = "Seleccionar el medio de pago que más te resulte entre las opciones disponibles y el proceso de compra será concluido. Recibirás un mail confirmando que hemos recibido tu pedido y lo estamos procesando. Una vez que validemos la orden  y tengamos la autorización de la tarjeta, tu compra quedará confirmada. Recibirás un mail confirmando la compra e indicando el nº de envío para que puedas seguirlo.";
export const done = "LISTO, ES FACIL, RAPIDO Y EN TAN SOLO UNOS CLICKS, TENES EL PRODUCTO EN TU CASA.";
export const paymentMethodTwo = "¿CUÁLES SON LOS MEDIOS DE PAGO?";
export const firstMethod = "Mercado Pago: Para 3 cuotas sin interés de los planes Ahora, podés utilizar las siguientes tarjetas de crédito: Visa, Mastercard o American Express .";
export const timeOfProduct = "¿CUÁNTO TARDA EN LLEGAR MI COMPRA?";
export const days = "Los plazos de entrega serán entre 5 Y 10 dias hábiles de lunes a viernes de 9 a 18 hs. El mismo varía según ámbito geográfico, localidad y sucursal de destino. En Cybermonday y Hotsale los plazos son de 10 a 15 dias habiles.";
export const finaly = "Los plazos elegidos para el despacho y entrega, se cuentan desde que la empresa haya validado la orden de compra y el medio de pago utilizado. En este momento llegara a tu casilla de e-mail, una confirmación de pedido completado."
