export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const ALL_CATEGORYS = "ALL_CATEGORYS";
export const FILTER_ORDER = "FILTER_ORDER";
export const PAGINATE = "PAGINATE";
export const CREATE_USER = "CREATE_USER";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const FILTER_PRICE = "FILTER_PRICE";

